serverUrl: https://eyesapi.applitools.com
apiKey: ${APPLITOOLS_API_KEY}
appName: Demo Checkbox App
viewport:
  width: 1200
  height: 800
matchLevel: Strict
browsers:
  - { width: 1200, height: 800, name: CHROME }
  - { width: 1200, height: 800, name: FIREFOX }
