serverUrl: https://eyesapi.applitools.com
apiKey: ${APPLITOOLS_API_KEY}
appName: Demo Checkbox App
viewport:
  width: 1200
  height: 800
matchLevel: Strict
browsersInfo:
  - browserType: chrome
    width: 1200
    height: 800
  - browserType: firefox
    width: 1200
    height: 800
  - deviceName: iPhone_X
    screenOrientation: portrait
  - deviceName: Pixel_2
    screenOrientation: portrait
